# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-04 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False, verbose_name='Viewed'),
        ),
    ]
